version: '3'

services:
  sinftools-postgres:
    container_name: sinftools_postgres
    image: postgres:12.0-alpine
    volumes:
      - ./data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=test
    networks:
      - postgres-compose-network
  # sinftools-pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
  #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
  #   ports:
      
  #     - "16543:80"
  #   depends_on:
  #     - sinftools-postgres
  #   networks:
  #     - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge
